package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.62

import (
	"context"
	"fmt"
	"manulatorre98/trading/graph/dolars"
	"manulatorre98/trading/graph/model"
)

// CreateDolar is the resolver for the createDolar field.
func (r *mutationResolver) CreateDollar(ctx context.Context) (*model.Dollar, error) {
	return dolars.CreateDollarResolver(r.DolarRepository)
}

// GetDolar is the resolver for the getDolar field.
func (r *queryResolver) GetDollar(ctx context.Context, date string) (*model.Dollar, error) {
	panic(fmt.Errorf("not implemented: GetDolar - getDolar"))
}

// GetDolarInDateRange is the resolver for the getDolarInDateRange field.
func (r *queryResolver) GetDollarInDateRange(ctx context.Context, startDate string, endDate string) ([]*model.Dollar, error) {
	panic(fmt.Errorf("not implemented: GetDolarInDateRange - getDolarInDateRange"))
}

// GetHistoricalDolar is the resolver for the getHistoricalDolar field.
func (r *queryResolver) GetHistoricalDollar(ctx context.Context) ([]*model.Dollar, error) {
	panic(fmt.Errorf("not implemented: GetHistoricalDolar - getHistoricalDolar"))
}
